/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_C_H_RPCGEN
#define _PART_C_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int a;
	int b;
	char path[256];
};
typedef struct inputs inputs;

#define BLACK_PROG 0x12345678
#define BLACK_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define part_c 1
extern  char ** part_c_1(inputs *, CLIENT *);
extern  char ** part_c_1_svc(inputs *, struct svc_req *);
extern int black_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define part_c 1
extern  char ** part_c_1();
extern  char ** part_c_1_svc();
extern int black_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_part_c_H_RPCGEN */
